name: squadio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.17.0
  http: ^0.13.4
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1
  equatable: ^2.0.3
  shimmer: ^2.0.0
  flash: ^2.0.3+2
  photo_view: ^0.14.0
  carousel_slider: ^4.1.1
  url_launcher: ^6.1.3
  readmore: ^2.1.0
  image_gallery_saver: ^1.7.1
  dio: ^4.0.6
  path_provider: ^2.0.11
  connectivity_plus: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3
  flutter_app_name: ^0.1.0
  flutter_native_splash: ^2.2.0+1

flutter:
  uses-material-design: true


# flutter pub run flutter_native_splash:create
flutter_native_splash:
  background_image: assets/splash.png
  android: true
  ios: true
  fullscreen: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

# flutter pub run flutter_app_name
flutter_app_name:
  name: "Squadio"