name: squadio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.17.0
  http: ^0.13.4
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1
  equatable: ^2.0.3
  shimmer: ^2.0.0
  fluttertoast: ^8.0.9
  photo_view: ^0.14.0
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
